### ISSUE TITLE
Only generic Resource definitions are output

### ISSUE THREAD

**Issue by cmaxwellau** [allinwonder/cfn2dsl#17]
```
  Resource("ImportDBInstance") do
    Type("AWS::RDS::DBInstance")
```

could be:

`  RDS_DBInstance("ImportDBInstance") do`

**Comment by sktan** [comment]
@cmaxwellau This looks to have been fixed if you gem install from the git repo directory.
The version needs to be bumped if you want to take advantage of this feature without pointing to github

@allinwonder

**Comment by cmaxwellau** [comment]
Yep can confirm this now works awesomely. What are the chances of getting rubygems.org updated?
