### ISSUE TITLE
include more Aws official templates in test cases

### ISSUE THREAD

**Issue by allinwonder** [allinwonder/cfn2dsl#4]
we are looking forward to cover all CFN supported resources and properties in our test cases

**Comment by yumpy** [comment]
You should take a look at https://github.com/neillturner/cfndsl_examples

**Comment by allinwonder** [comment]
To have better test coverage, it needs to test all support attributes, functions in our code. It is not wise to just include more cfn templates. Close this issue and create individual issues for uncovered properties.
